---

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install k8s packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ k8s_packages }}"

- name: Ensure kubelet directory exists
  file:
    path: /var/lib/kubelet
    state: directory
    mode: '0775'

- name: Configure kubelet node IP via template
  template:
    src: kubeadm-flags.env.j2
    dest: /var/libe/kubelet/kubeadm-flags.env
    owner: root
    group: root
    mode: '0644'
  notify: restart kubelet
