#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s_base

- name: Install k8s packages
  import_tasks: k8s_packages.yml
  tags:
    - k8s_packages
- name: Configure containerd config toml
  import_tasks: containerd_config.yml
  tags:
    - k8s_packages
