---

- name: Fail if system is not systemd managed
  ansible.builtin.fail:
    msg: "Warning: this system does not use systemd"
  when: >
    (
      ansible_os_family == 'Windows'
      or
      ansible_service_mgr != 'systemd'
    )

- name: Ensure required kernel modules are loaded
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ base_kernel_modules }}"

- name: Ensure required kernel modules load at boot
  ansible.builtin.copy:
    src: k8s-modules.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure kernel parameters for Kubernetes
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: yes
    state: present
  loop: "{{ k8s_sysctl_conf }}"
