#SPDX-License-Identifier: MIT-0
---
# tasks file for platform_pi

- name: Configure fan controls
  import_tasks: fan_control.yml
  tags:
    - fan_control
- name: Overwrite Bootloader firmware dtb
  import_tasks: bootloader_override.yml
  tags:
    - bootloader
