---
- name: handlers
  hosts: suarm16wrk001
  tasks:
    - name: Install apache
      ansible.builtin.package:
        name: apache2
        state: latest
    - name: start httpd
      ansible.builtin.service:
        name: apache2
        state: started
    - name: Modify config
      ansible.builtin.lineinfile:
        path: /etc/apache2/apache2.conf
        line: "# Managed by ansible"
        insertafter: EOF
      notify: restart httpd
  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
