#SPDX-License-Identifier: MIT-0
---
# vars file for base_unix_os

base_kernel_modules:
  - overlay
  - br_netfilter

base_packages:
  - name: curl
    note: HTTP client

  - name: avahi-daemon
    note: Enables host.local mDNS

  - name: sysstat
    note: Robust system metrics

  - name: ca-certificates
    note: Trusted certificates bundle for HTTPS package downloads

  - name: jq
    note: JSON query tool, useful for querying active state of things

k8s_sysctl_conf:
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
