#SPDX-License-Identifier: MIT-0
---
# vars file for base_unix_os

base_kernel_modules:
  - overlay
  - br_netfilter

base_packages:
  - name: curl
    note: HTTP client

  - name: avahi-daemon
    note: Enables host.local mDNS

  - name: systat
    note: Robust system metrics

  - name: ca-certificates
    note: Trusted certificates bundle for HTTPS package downloads

base_packages:
  - name: containerd.io
    note: Container runtime

  - name: kubelet
    note: Kubernetes node agent

  - name: kubeadm
    note: Kubernetes cluster bootstrap tool

  - name: kubectl
    note: Kubernetes CLI
